Tablet/Controllers/ProjectController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Tablet.Data.interfaces;
using Tablet.Data.Models;
using Tablet.ViewModels;

namespace Tablet.Controllers
{
    public class ProjectController : Controller
    {

        private readonly IProject project;
        private readonly ProjectModels projectModels;

        public ProjectController(IProject project, ProjectModels projectModels)
        {
            this.project = project;
            this.projectModels = projectModels;
        }

        public IActionResult Presentation()
        {

            return View();
        }

        [HttpPost]
        public IActionResult Presentation(Project project)
        {
            projectModels.AddToTable(project.Id, project.Name, project.Customer, project.Developer, project.Technology, project.Cost);
            return View();
        }

        public IActionResult Editor()
        {

            return View();
        }
    }
}

Tablet/Controllers/ProjectPageController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Tablet.Data.Models;
using Tablet.ViewModels;
using iTextSharp.text;
using iTextSharp.text.pdf;
using System.IO;

namespace Tablet.Controllers
{
    public class ProjectPageController : Controller
    {
        private readonly ProjectPageModel projectPageModel;
        private static String id;
        private static String name;

        public ProjectPageController(ProjectPageModel projectPageModel)
        {
            this.projectPageModel = projectPageModel;
        }


        public ViewResult Index()
        {
            ProjectPageViewModel.projectId = id;

            var items = projectPageModel.getProjectModels(ProjectPageController.id);
            projectPageModel.Project = items;

            var secondItems = projectPageModel.GetProjectProblemsModels();
            projectPageModel.projectProblems = secondItems;

            var thirdItems = projectPageModel.GetProjectStagesModels();
            projectPageModel.Stages = thirdItems;

            var fourthItems = projectPageModel.GetProjectGeneralProblems(ProjectPageController.id);
            projectPageModel.GeneralProblems = fourthItems;

            var fifthItems = projectPageModel.GetProjectGeneralWorks();
            projectPageModel.GeneralWorks = fifthItems;

            var sixthItems = projectPageModel.GetProjectRisks();
            projectPageModel.ProjectRisks = sixthItems;

            var obj = new ProjectPageViewModel
            {
                projectPageModel = this.projectPageModel,

            };
            
            return View(obj);
        }

        public RedirectToActionResult getProjectId(string id)
        {
            ProjectPageController.id = id;
            return RedirectToAction("Index");
        }

        public ViewResult AddProblem()
        {
            return View();
        }

        [HttpPost]
        public RedirectToActionResult AddProblem(ProjectProblems projectProblems)
        {
            projectPageModel.AddToProjectProblems(projectProblems.Id, id, projectProblems.Problem);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public RedirectToActionResult DeleteProblem(int ID)
        {
            projectPageModel.DeleteProjectProblems(ID, id);
            return RedirectToAction("Index");
        }

        public ViewResult AddStage()
        {
            return View();
        }

        [HttpPost]
        public RedirectToActionResult AddStage(Stages stages)
        {
            projectPageModel.AddToProjectStage(stages.Id, id, stages.Stage);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public RedirectToActionResult DeleteStage(int ID)
        {
            projectPageModel.DeleteProjectStage(ID, id);
            return RedirectToAction("Index");
        }

        public ViewResult AddGeneralProblem()
        {
            return View();
        }

        [HttpPost]
        public RedirectToActionResult AddGeneralProblem(ProjectGeneralProblems projectGeneralProblems)
        {
            projectPageModel.AddToProjectGeneralProblems(projectGeneralProblems.Description, projectGeneralProblems.Date, id);
            return RedirectToAction("Index");
        }

        public ViewResult AddGeneralWorks()
        {
            return View();
        }

        [HttpPost]
        public RedirectToActionResult AddGeneralWorks(ProjectGeneralWorks projectGeneralWorks)
        {
            projectPageModel.AddToProjectGeneralWorks(projectGeneralWorks.Description, projectGeneralWorks.Date,
                projectGeneralWorks.RedLine,  projectGeneralWorks.Responsible, projectGeneralWorks.Persent, id);
            return RedirectToAction("Index");
        }

        public ViewResult AddRisks()
        {
            return View();
        }

        [HttpPost]
        public RedirectToActionResult AddRisks(ProjectRisks projectRisks)
        {
            
            projectPageModel.AddToProjectRisks(projectRisks.Description, projectRisks.OTV,
                projectRisks.RedLine, projectRisks.Solution, id);
            return RedirectToAction("Index");
        }


        [HttpPost]
        public RedirectToActionResult Editor(Project project)
        {
            projectPageModel.EditToProject(id, project.Customer, project.Developer,
                project.Technology, project.FinalDate, project.Cost);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public RedirectToActionResult DeleteFinalProblems(int ID)
        {
            projectPageModel.DeleteGeneralProblems(ID);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public RedirectToActionResult DeleteGeneralWorks(int ID)
        {
            projectPageModel.DeleteGeneralWorks(ID);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public RedirectToActionResult DeleteRisks(int ID)
        {
            projectPageModel.DeleteProjectRisks(ID);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public RedirectToActionResult ChangeStage(int id)
        {
            ProjectPageViewModel.Stage = id;
            return RedirectToAction("Index");
        }

        public RedirectToActionResult MakePDF()
        {
            iTextSharp.text.Document doc = new iTextSharp.text.Document();
            PdfWriter.GetInstance(doc, new FileStream("C:\\ProjectId\\"  + (id) +"_Project.pdf", FileMode.Create));
            doc.Open();

            string ttf = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.Fonts), "ARIAL.TTF");
            BaseFont baseFont = BaseFont.CreateFont(ttf, BaseFont.IDENTITY_H, BaseFont.NOT_EMBEDDED);
            iTextSharp.text.Font font = new iTextSharp.text.Font(baseFont, iTextSharp.text.Font.DEFAULTSIZE, iTextSharp.text.Font.NORMAL);

            PdfPCell cell = new PdfPCell(new Phrase("Общая информация о проекте", font));
            PdfPTable table = new PdfPTable(6);
            cell.Colspan = 6;
            cell.HorizontalAlignment = 1;
            cell.Border = 0;
            table.AddCell(cell);
            cell = new PdfPCell(new Phrase(new Phrase("Номер", font)));
            table.AddCell(cell);
            cell = new PdfPCell(new Phrase(new Phrase("Название", font)));
            table.AddCell(cell);
            cell = new PdfPCell(new Phrase(new Phrase("Заказчик", font)));
            table.AddCell(cell);
            cell = new PdfPCell(new Phrase(new Phrase("Разработчик", font)));
            table.AddCell(cell);
            cell = new PdfPCell(new Phrase(new Phrase("Технология", font)));
            table.AddCell(cell);
            cell = new PdfPCell(new Phrase(new Phrase("Стоимость", font)));
            table.AddCell(cell);
            var items = projectPageModel.getProjectModels(id);
            
            if (items != null)
            {
                foreach (var el in items)
                {
                    if (el.Id.Equals(id))
                    {
                        table.AddCell(new Phrase(el.Id, font));
                        table.AddCell(new Phrase(el.Name.ToString(), font));
                        table.AddCell(new Phrase(el.Customer, font));
                        table.AddCell(new Phrase(el.Developer.ToString(), font));
                        table.AddCell(new Phrase(el.Technology.ToString(), font));
                        table.AddCell(new Phrase(el.Cost.ToString(), font));
                    }
                }
            }


            doc.Add(table);
            doc.Add(new Paragraph("\n\n"));

            cell = new PdfPCell(new Phrase("Этапы", font));
            table = new PdfPTable(2);
            cell.Colspan = 2;
            cell.HorizontalAlignment = 1;
            cell.Border = 0;
            table.AddCell(cell);
            cell = new PdfPCell(new Phrase(new Phrase("Номер", font)));
            table.AddCell(cell);
            cell = new PdfPCell(new Phrase(new Phrase("Этап", font)));
            table.AddCell(cell);
            var items2 = projectPageModel.GetProjectStagesModels();
            
            if (items2 != null)
            {
                foreach (var el in items2)
                {
                    
                    if (el.ProjectId.Equals(id))
                    {
                        table.AddCell(new Phrase(el.Id.ToString(), font));
                        table.AddCell(new Phrase(el.Stage.ToString(), font));
                    }
                }
            }


            doc.Add(table);
            doc.Add(new Paragraph("\n\n"));


            cell = new PdfPCell(new Phrase("Задачи до конца проекта", font));
            table = new PdfPTable(2);
            cell.Colspan = 2;
            cell.HorizontalAlignment = 1;
            cell.Border = 0;
            table.AddCell(cell);
            cell = new PdfPCell(new Phrase(new Phrase("Номер", font)));
            table.AddCell(cell);
            cell = new PdfPCell(new Phrase(new Phrase("Название", font)));
            table.AddCell(cell);

            var items3 = projectPageModel.GetProjectProblemsModels();

            if (items3 != null)
            {
                foreach (var el in items3)
                {
                    if (el.ProjectId.Equals(id))
                    {
                        table.AddCell(new Phrase(el.Id.ToString(), font));
                        table.AddCell(new Phrase(el.Problem.ToString(), font));
                    }
                }
            }


            doc.Add(table);
            doc.Add(new Paragraph("\n\n"));


            cell = new PdfPCell(new Phrase("Основные задачи этапа", font));
            table = new PdfPTable(2);
            cell.Colspan = 2;
            cell.HorizontalAlignment = 1;
            cell.Border = 0;
            table.AddCell(cell);

Tablet/Views/Project/Editor.cshtml
@model Project

    <div class="container  mt-5 mb-5">
        <header>
            <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
                <div class="navbar-collapse" id="navbarСollapse">
                    <ul class="navbar-nav mr-auto">

                        <li class="nav-item active">
                            <a class="nav-link" href="/Home/Index">Главная</a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" href="/ProjectPage/Index">Подробная информация</a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" href="/Restrictions/Index">Ограничения</a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" href="/MeetingPage/GetList">Встречи по проекту</a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" href="/GeneralInformation/Index">Исполнение проекта</a>
                        </li>

                    </ul>

                    <form class="form-inline mt-2 mt-md-0">
                        <a class="nav-link" href="/Account/Logout">Выйти</a>
                    </form>
                </div>
            </nav>

        </header>
        <hr />
        <hr />
        <div class="currencies float-left">
            <h2>
                Добавление значения
            </h2>

        </div>
        <hr />
        <hr />
        <hr />
        <form asp-action="Editor" asp-controller="ProjectPage" method="post" class="form">
            <div class="form-group">
                <label asp-for="Customer"></label>
                <div class="col-md-5">
                    <input asp-for="Customer" class="form-control" />
                </div>
            </div>
            <div class="form-group">
                <label asp-for="Developer"></label>
                <div class="col-md-5">
                    <input asp-for="Developer" class="form-control" />
                </div>
            </div>
            <div class="form-group">
                <label asp-for="Technology"></label>
                <div class="col-md-5">
                    <input asp-for="Technology" class="form-control" />
                </div>
            </div>
            <div class="form-group">
                <label asp-for="FinalDate"></label>
                <div class="col-md-5">
                    <input asp-for="FinalDate" class="form-control" />
                </div>
            </div>
            <div class="form-group">
                <label asp-for="Cost"></label>
                <div class="col-md-5">
                    <input asp-for="Cost" class="form-control" />
                </div>
            </div>
            <input class="btn btn-success" type="submit" value="Добавить в таблицу" />
        </form>
    </div>

Tablet/Views/Project/Presentation.cshtml
@model Project

    <div class="container  mt-5 mb-5">
        <header>
            <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
                <div class="navbar-collapse" id="navbarСollapse">
                    <ul class="navbar-nav mr-auto">

                        <li class="nav-item active">
                            <a class="nav-link" href="/Home/Index">Главная</a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" href="/ProjectPage/Index">Подробная информация</a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" href="/Restrictions/Index">Ограничения</a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" href="/MeetingPage/GetList">Встречи по проекту</a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" href="/GeneralInformation/Index">Исполнение проекта</a>
                        </li>

                    </ul>

                    <form class="form-inline mt-2 mt-md-0">
                        <a class="nav-link" href="/Account/Logout">Выйти</a>
                    </form>
                </div>
            </nav>

        </header>
        <hr />
        <hr />
        <div class="currencies float-left">
            <h2>
                Добавление значения
            </h2>

        </div>
        <hr />
        <hr />
        <hr />
        <form asp-action="Presentation" method="post" class="form">
            <div class="form-group">
                <label asp-for="Id"></label>
                <div class="col-md-5">
                    <input asp-for="Id" class="form-control" />
                    <span asp-validation-for="Id" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="Name"></label>
                <div class="col-md-5">
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
            </div>
            <div class="form-group">
                <label asp-for="Customer"></label>
                <div class="col-md-5">
                    <input asp-for="Customer" class="form-control" />
                </div>
            </div>
            <div class="form-group">
                <label asp-for="Developer"></label>
                <div class="col-md-5">
                    <input asp-for="Developer" class="form-control" />
                </div>
            </div>
            <div class="form-group">
                <label asp-for="Technology"></label>
                <div class="col-md-5">
                    <input asp-for="Technology" class="form-control" />
                </div>
            </div>
            <div class="form-group">
                <label asp-for="Cost"></label>
                <div class="col-md-5">
                    <input asp-for="Cost" class="form-control" />
                </div>
            </div>
            <input class="btn btn-success" type="submit" value="Добавить в таблицу" />
        </form>
    </div>