Tablet/Controllers/GeneralDevelopmentController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Tablet.Data.interfaces;
using Tablet.Data.Models;
using Microsoft.AspNetCore.Authorization;

namespace Tablet.Controllers
{
    public class GeneralDevelopmentController : Controller
    {

        private readonly MainModel mainModel;

        public GeneralDevelopmentController(MainModel mainModel)
        {

            this.mainModel = mainModel;
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Checkout()
        {
            
            return View();
        }

        [HttpPost]
        public IActionResult Checkout(GeneralDevelopment general)
        {
            mainModel.AddToTable(general.Id, general.Date, general.Forecast, general.Progress);
            return View();
        }

        [HttpPost]
        public RedirectToActionResult DeleteValue(String Id)
        {
            mainModel.DeleteFromProgressTable(Id);
            return RedirectToAction("Index", "GeneralInformation");
        }
    }
}

Tablet/Controllers/GeneralInformationController.cs
using Microsoft.AspNetCore.Mvc;
using Tablet.ViewModels;
using Tablet.Data.interfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Tablet.Data.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.RazorPages;
using iTextSharp;
using iTextSharp.text;
using iTextSharp.text.pdf;
using System.IO;
using Microsoft.Extensions.Configuration;

namespace Tablet.Controllers
{
    public class GeneralInformationController : Controller
    {

        private readonly MainModel mainModel;

        public GeneralInformationController(MainModel mainModel)
        {
            this.mainModel = mainModel;
        }

        public IConfiguration Configuration { get; }

        public IActionResult Index()
        {
            if (HomeViewModel.measurement == null)
                HomeViewModel.measurement = "Трудозатраты";
            var items = mainModel.getGeneralDevelopmentModels();
            mainModel.generalDevelopmentModels = items;

            var secondItems = mainModel.GetStructures();
            mainModel.Structures = secondItems;

            var thirdItem = mainModel.GetInformation();
            InformationModel[] array = thirdItem.ToArray();
            if (array.Length != 0 && array[0].Id.Equals("1"))
            {
                HomeViewModel.measurement = array[0].Information;
            }

            var obj = new HomeViewModel
            {
                mainModel = this.mainModel
            };

            return View(obj);
        }

        [HttpPost]
        public RedirectToActionResult ChangeMeasurement(String measurement)
        {
            HomeViewModel.measurement = measurement;
            mainModel.AddToTableInformation(measurement);
            return RedirectToAction("Index");
        }

        public RedirectToActionResult MakePDF()
        {
            iTextSharp.text.Document doc = new iTextSharp.text.Document();
            PdfWriter.GetInstance(doc, new FileStream("C:\\ProjectId\\HomePage.pdf", FileMode.Create));
            doc.Open();

            string ttf = Path.Combine(Environment.GetFolderPath(Environment.SpecialFolder.Fonts), "ARIAL.TTF");
            BaseFont baseFont = BaseFont.CreateFont(ttf, BaseFont.IDENTITY_H, BaseFont.NOT_EMBEDDED);
            iTextSharp.text.Font font = new iTextSharp.text.Font(baseFont, iTextSharp.text.Font.DEFAULTSIZE, iTextSharp.text.Font.NORMAL);
            

            PdfPCell cell = new PdfPCell(new Phrase("Готовность проекта", font));
            PdfPTable table = new PdfPTable(3);
            cell.Colspan = 3;
            cell.HorizontalAlignment = 1;
            cell.Border = 0;
            table.AddCell(cell);
            cell = new PdfPCell(new Phrase(new Phrase("Дата", font)));
            table.AddCell(cell);
            cell = new PdfPCell(new Phrase(new Phrase("Прогноз", font)));
            table.AddCell(cell);
            cell = new PdfPCell(new Phrase(new Phrase("Факт", font)));
            table.AddCell(cell);
            var items = mainModel.getGeneralDevelopmentModels();
            if (items != null)
            {
                foreach (var el in items)
                {
                    table.AddCell(new Phrase(el.Date.ToString(), font));
                    table.AddCell(new Phrase(el.Forecast.ToString(), font));
                    table.AddCell(new Phrase(el.Progress.ToString(), font));
                }
            }


            doc.Add(table);
            doc.Add(new Paragraph("\n\n"));

            cell = new PdfPCell(new Phrase("Структура проекта", font));
            table = new PdfPTable(2);
            cell.Colspan = 2;
            cell.HorizontalAlignment = 1;
            cell.Border = 0;
            table.AddCell(cell);
            cell = new PdfPCell(new Phrase(new Phrase("Наименование", font)));
            table.AddCell(cell);
            cell = new PdfPCell(new Phrase(new Phrase("Проценты", font)));
            table.AddCell(cell);
            var items2 = mainModel.GetStructures();
            if (items2 != null)
            {
                foreach (var el in items2)
                {
                    table.AddCell(new Phrase(el.Name, font));
                    table.AddCell(new Phrase(el.Proportion.ToString(), font));
                }
            }


            doc.Add(table);

            doc.Close();
            return RedirectToAction("Index");
        }

    }
}

Tablet/Controllers/StructureController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Tablet.Data.interfaces;
using Tablet.Data.Models;
using Microsoft.AspNetCore.Authorization;

namespace Tablet.Controllers
{
    public class StructureController : Controller
    {

        private readonly MainModel mainModel;

        public StructureController (MainModel mainModel)
        {
            this.mainModel = mainModel;
        }

        [Authorize(Roles = "Admin")]
        public IActionResult SecondCheckout()
        {

            return View();
        }

        [HttpPost]
        public IActionResult SecondCheckout(Structure structure)
        {
            mainModel.AddToTableStructure(structure.Name, structure.Proportion, structure.Plan);
            return View();
        }

        [HttpPost]
        public RedirectToActionResult DeleteValue(String Id)
        {
            mainModel.DeleteFromStructureTable(Id);
            return RedirectToAction("Index", "GeneralInformation");
        }
    }
}

Tablet/Views/GeneralInformation/Index.cshtml
@model Tablet.ViewModels.HomeViewModel

    <div class="container mt-5 mb-5">
        <header>
            <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
                <div class="navbar-collapse" id="navbarСollapse">
                    <ul class="navbar-nav mr-auto">

                        <li class="nav-item active">
                            <a class="nav-link" href="/Home/Index">Главная</a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" href="/ProjectPage/Index">Подробная информация</a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" href="/Restrictions/Index">Ограничения</a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" href="/MeetingPage/GetList">Встречи по проекту</a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" href="/GeneralInformation/Index">Исполнение проекта</a>
                        </li>

                    </ul>

                    <form class="form-inline mt-2 mt-md-0">
                        <a class="nav-link" href="/Account/Logout">Выйти</a>
                    </form>
                </div>
            </nav>

        </header>
        <br><br>
        <div class="currencies float-left">
            <h2>
                Готовность проекта
            </h2>

        </div>
        <br><br><br>
        <table class="table">
            <tr><td>Дата</td><td>Прогноз</td><td>Факт</td></tr>
            @foreach (var item in Model.mainModel.generalDevelopmentModels)

            {
                <tr>
                    <td>@item.Date</td>
                    <td>@item.Forecast</td>
                    <td>@item.Progress</td>
                    <td>
                        <form method="post">
                            <button type="submit" asp-controller="GeneralDevelopment" asp-action="DeleteValue" asp-route-id="@item.Id">
                                Удалить
                            </button>
                        </form>
                    </td>

                </tr>
            }
        </table>
        <br><br>
        @if (User.IsInRole("Admin"))
        {
            <a class="btn badge-light border-dark" href="/GeneralDevelopment/Checkout">Добавить значение</a>
        }



        <hr />
        <div class="currencies float-left">
            <h2>
                Структура расходов
            </h2>

        </div>
        <br><br><br>
        <table class="table">

            <tr>
                <td>Название, единица измерения: </td>
                <td>Факт </td>
                <td>План </td>
                <td>
                    @using (Html.BeginForm("ChangeMeasurement", "Home"))
                    {
                        <input type="text" id="ss" name="measurement" value="@HomeViewModel.measurement" />
                        <input type="submit" value="Изменить" style="display:none;" />
                    }
                </td>
            </tr>
            @foreach (var item in Model.mainModel.Structures)
            {
        <tr>
            <td>@item.Name</td>
            <td>@item.Proportion</td>
            <td>@item.Plan</td>
            <td>
                <form method="post">
                    <button type="submit" asp-controller="Structure" asp-action="DeleteValue" asp-route-id="@item.Id">
                        Удалить
                    </button>
                </form>
            </td>
        </tr>
            }
        </table>
        <br><br>
        @if (User.IsInRole("Admin"))
        {
            <a class="btn badge-light border-dark" href="/Structure/SecondCheckout">Добавить значение</a>
            <br>
        }
        <br>
        <a class="btn badge-light border-dark" href="/Home/MakePDF">Создать отчет</a>

    </div>