Tablet/Controllers/RestrictionsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using Tablet.Data.Models;
using Tablet.ViewModels;

namespace Tablet.Controllers
{
    public class RestrictionsController : Controller
    {
        private readonly RestrictionsPageModel restrictionsPageModel;

        public RestrictionsController(RestrictionsPageModel restrictionsPageModel)
        {
            this.restrictionsPageModel = restrictionsPageModel;
        }

        public IActionResult Index()
        {
            var items = restrictionsPageModel.getRestrictions();
            restrictionsPageModel.Restrictions = items;

            
            var obj = new RestrictionsPageViewModel
            {
                RestrictionsPage = this.restrictionsPageModel

            };

            RestrictionsPageViewModel.ProjectId = ProjectPageViewModel.projectId;

            return View(obj);
        }

        [HttpPost]
        public RedirectToActionResult EditFinance(String id, String value)
        {
            restrictionsPageModel.Edit(id, "Finance", value);
            return RedirectToAction("Index");
        }
        [HttpPost]
        public RedirectToActionResult EditArchitecture(String id, String value)
        {
            restrictionsPageModel.Edit(id, "Architecture", value);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public RedirectToActionResult EditSafety(String id, String value)
        {
            restrictionsPageModel.Edit(id, "Safety", value);
            return RedirectToAction("Index");
        }
        [HttpPost]
        public RedirectToActionResult EditData(String id, String value)
        {
            restrictionsPageModel.Edit(id, "Data", value);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public RedirectToActionResult EditRedLine(String id, String value)
        {
            restrictionsPageModel.Edit(id, "RedLine", value);
            return RedirectToAction("Index");
        }
        [HttpPost]
        public RedirectToActionResult EditDocument(String id, String value)
        {
            restrictionsPageModel.Edit(id, "Document", value);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public RedirectToActionResult EditInfrastructure(String id, String value)
        {
            restrictionsPageModel.Edit(id, "Infrastructure", value);
            return RedirectToAction("Index");
        }
        [HttpPost]
        public RedirectToActionResult EditLicense(String id, String value)
        {
            restrictionsPageModel.Edit(id, "License", value);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public RedirectToActionResult EditDateTime(String id, DateTime value)
        {
            restrictionsPageModel.EditDateTime(id, value);
            return RedirectToAction("Index");
        }

        public ViewResult AddTable()
        {
            return View();
        }


        public ViewResult EditTable(String id)
        {
            var items = restrictionsPageModel.getRestrictions();
            restrictionsPageModel.Restrictions = items;


            var obj = new RestrictionsPageViewModel
            {
                RestrictionsPage = this.restrictionsPageModel

            };
            RestrictionsPageViewModel.Id = id;
            return View(obj);
        }
        [HttpPost]
        public RedirectToActionResult AddTable(Restrictions restrictions)
        {
            String id = Guid.NewGuid().ToString();
            restrictionsPageModel.AddRestrictions(id, ProjectPageViewModel.projectId, restrictions.DateTime);
            return RedirectToAction("Index");
        }
    }
}

Tablet/Views/Restrictions/AddTable.cshtml
@model Restrictions

<div class="container  mt-5 mb-5">
    <header>
        <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
            <div class="navbar-collapse" id="navbarСollapse">
                <ul class="navbar-nav mr-auto">

                    <li class="nav-item active">
                        <a class="nav-link" href="/Home/Index">Главная</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="/ProjectPage/Index">Подробная информация</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="/Restrictions/Index">Ограничения</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="/MeetingPage/GetList">Встречи по проекту</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="/GeneralInformation/Index">Исполнение проекта</a>
                    </li>

                </ul>

                <form class="form-inline mt-2 mt-md-0">
                    <a class="nav-link" href="/Account/Logout">Выйти</a>
                </form>
            </div>
        </nav>

    </header>
    <hr />
    <hr />
    <div class="currencies float-left">
        <h2>
            Добавление значения
        </h2>

    </div>
    <hr />
    <hr />

    <form asp-action="AddTable" method="post" class="form">
        <hr />
        <hr />
        <div class="form-group">
            <label asp-for="DateTime"></label>
            <div class="col-md-12">
                <input asp-for="DateTime" class="form-control" />
                <span asp-validation-for="DateTime" class="text-danger"></span>
            </div>
        </div>
        <input class="btn btn-success" type="submit" value="Добавить таблицу" />
    </form>
</div>

Tablet/Views/Restrictions/EditTable.cshtml
@model RestrictionsPageViewModel
<div>
    <header>
        <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
            <div class="navbar-collapse" id="navbarСollapse">
                <ul class="navbar-nav mr-auto">

                    <li class="nav-item active">
                        <a class="nav-link" href="/Home/Index">Главная</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="/ProjectPage/Index">Подробная информация</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="/Restrictions/Index">Ограничения</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="/MeetingPage/GetList">Встречи по проекту</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="/GeneralInformation/Index">Исполнение проекта</a>
                    </li>

                </ul>

                <form class="form-inline mt-2 mt-md-0">
                    <a class="nav-link" href="/Account/Logout">Выйти</a>
                </form>
            </div>
        </nav>

    </header>
    <br />
    <br />
    <h2>
        Изменение значений таблицы <br />
    </h2>
    <style type="text/css">
        body {
        }

        table {
            width: 100%; /* Ширина таблицы */
        }

        td {
            padding: 9px 8px;
            width: 100px;
        }

            td.col1 {
                background: red;
                color: white;
            }

            td.col2 {
                background: orange;
                color: gray;
            }

            td.col3 {
                background: green;
            }
    </style>
    
            @foreach (var item in Model.RestrictionsPage.Restrictions)
            {
                if (item.Id.Equals(RestrictionsPageViewModel.Id))
                {
                    <td>
                            Изменение даты таблицы
                    </td>

                    @using (Html.BeginForm("EditDateTime", "Restrictions"))
                    {
                        <input type="submit" id="ss" name="id" value="@item.Id" style="display:none;" />
                        <input type="date" id="ss" name="value" value="@item.DateTime" />
                        <input type="submit" value="Изменить" style="display:none;" />
                    }

                    <br />
                    <table class="table">
                        <tr>
                            <td>Название</td>
                            <td>Цвет</td>
                            <td>Хорошо/Плохо/Удовлетворительно</td>
                        </tr>
                        <tr>
                            <td>Финансы</td>

                            @if (item.Finance != null && item.Finance.Equals("Хорошо"))
                            {
                                <td class="col3"></td>
                            }
                            else if (item.Finance != null && item.Finance.Equals("Плохо"))
                            {
                                <td class="col1"></td>
                            }
                            else
                            {
                                <td class="col2"></td>
                            }

                            <td>
                                @using (Html.BeginForm("EditFinance", "Restrictions"))
                                {
                                    <input type="submit" id="ss" name="id" value="@item.Id" style="display:none;" />
                                    <input type="text" id="ss" name="value" value="@item.Finance" />
                                    <input type="submit" value="Изменить" style="display:none;" />
                                }
                            </td>
                        </tr>
                        <tr>
                            <td>Архитектура</td>
                            @if (item.Architecture != null && item.Architecture.Equals("Хорошо"))
                            {
                                <td class="col3"></td>
                            }
                            else if (item.Architecture != null && item.Architecture.Equals("Плохо"))
                            {
                                <td class="col1"></td>
                            }
                            else
                            {
                                <td class="col2"></td>
                            }
                            <td>
                                @using (Html.BeginForm("EditArchitecture", "Restrictions"))
                                {
                                    <input type="submit" id="ss" name="id" value="@item.Id" style="display:none;" />
                                    <input type="text" id="ss" name="value" value="@item.Architecture" />
                                    <input type="submit" value="Изменить" style="display:none;" />
                                }
                            </td>
                        </tr>
                        <tr>
                            <td>Безопасность</td>
                            @if (item.Safety != null && item.Safety.Equals("Хорошо"))
                            {
                                <td class="col3"></td>
                            }
                            else if (item.Safety != null && item.Safety.Equals("Плохо"))
                            {
                                <td class="col1"></td>
                            }
                            else
                            {
                                <td class="col2"></td>
                            }
                            <td>
                                @using (Html.BeginForm("EditSafety", "Restrictions"))
                                {
                                    <input type="submit" id="ss" name="id" value="@item.Id" style="display:none;" />
                                    <input type="text" id="ss" name="value" value="@item.Safety" />
                                    <input type="submit" value="Изменить" style="display:none;" />
                                }
                            </td>
                        </tr>
                        <tr>
                            <td>Данные</td>
                            @if (item.Data != null && item.Data.Equals("Хорошо"))
                            {
                                <td class="col3"></td>
                            }
                            else if (item.Data != null && item.Data.Equals("Плохо"))
                            {
                                <td class="col1"></td>
                            }
                            else
                            {
                                <td class="col2"></td>
                            }
                            <td>
                                @using (Html.BeginForm("EditData", "Restrictions"))
                                {
                                    <input type="submit" id="ss" name="id" value="@item.Id" style="display:none;" />
                                    <input type="text" id="ss" name="value" value="@item.Data" />
                                    <input type="submit" value="Изменить" style="display:none;" />
                                }
                            </td>
                        </tr>
                        <tr>
                            <td>Сроки</td>
                            @if (item.RedLine != null && item.RedLine.Equals("Хорошо"))
                            {
                                <td class="col3"></td>
                            }
                            else if (item.RedLine != null && item.RedLine.Equals("Плохо"))
                            {
                                <td class="col1"></td>
                            }
                            else
                            {
                                <td class="col2"></td>
                            }
                            <td>
                                @using (Html.BeginForm("EditRedLine", "Restrictions"))
                                {
                                    <input type="submit" id="ss" name="id" value="@item.Id" style="display:none;" />
                                    <input type="text" id="ss" name="value" value="@item.RedLine" />
                                    <input type="submit" value="Изменить" style="display:none;" />
                                }
                            </td>
                        <tr>
                            <td>Документ</td>
                            @if (item.Document != null && item.Document.Equals("Хорошо"))
                            {
                                <td class="col3"></td>
                            }
                            else if (item.Document != null && item.Document.Equals("Плохо"))
                            {
                                <td class="col1"></td>
                            }
                            else
                            {
                                <td class="col2"></td>
                            }
                            <td>
                                @using (Html.BeginForm("EditDocument", "Restrictions"))
                                {
                                    <input type="submit" id="ss" name="id" value="@item.Id" style="display:none;" />
                                    <input type="text" id="ss" name="value" value="@item.Document" />
                                    <input type="submit" value="Изменить" style="display:none;" />
                                }
                            </td>
                        </tr>
                        <tr>
                            <td>Инфраструктура</td>
                            @if (item.Infrastructure != null && item.Infrastructure.Equals("Хорошо"))
                            {
                                <td class="col3"></td>
                            }
                            else if (item.Infrastructure != null && item.Infrastructure.Equals("Плохо"))
                            {
                                <td class="col1"></td>
                            }
                            else
                            {
                                <td class="col2"></td>
                            }
                            <td>
                                @using (Html.BeginForm("EditInfrastructure", "Restrictions"))
                                {
                                    <input type="submit" id="ss" name="id" value="@item.Id" style="display:none;" />
                                    <input type="text" id="ss" name="value" value="@item.Infrastructure" />
                                    <input type="submit" value="Изменить" style="display:none;" />
                                }
                            </td>
                        <tr>
                            <td>Лицензия</td>
                            @if (item.License != null && item.License.Equals("Хорошо"))
                            {
                                <td class="col3"></td>
                            }
                            else if (item.License != null && item.License.Equals("Плохо"))
                            {
                                <td class="col1"></td>
                            }
                            else
                            {
                                <td class="col2"></td>
                            }
                            <td>
                                @using (Html.BeginForm("EditLicense", "Restrictions"))
                                {
                                    <input type="submit" id="ss" name="id" value="@item.Id" style="display:none;" />
                                    <input type="text" id="ss" name="value" value="@item.License" />
                                    <input type="submit" value="Изменить" style="display:none;" />
                                }
                            </td>
                        </tr>

                    </table>
                }
            }

            <hr />
            
</div>

Tablet/Views/Restrictions/Index.cshtml
@model RestrictionsPageViewModel
<div>
    <header>
        <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
            <div class="navbar-collapse" id="navbarСollapse">
                <ul class="navbar-nav mr-auto">

                    <li class="nav-item active">
                        <a class="nav-link" href="/Home/Index">Главная</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="/ProjectPage/Index">Подробная информация</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="/Restrictions/Index">Ограничения</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="/MeetingPage/GetList">Встречи по проекту</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="/GeneralInformation/Index">Исполнение проекта</a>
                    </li>


                </ul>

                <form class="form-inline mt-2 mt-md-0">
                    <a class="nav-link" href="/Account/Logout">Выйти</a>
                </form>
            </div>
        </nav>

    </header>
    <br />
    <br />
    <h2>
        Таблицы ограничений проекта <br />
    </h2>
    <style type="text/css">
        body {
        }

        table {
            width: 100%; /* Ширина таблицы */
        }

        td {
            padding: 9px 8px;
            width: 100px;
        }

            td.col1 {
                background: red;
                color: white;
            }

            td.col2 {
                background: orange;
                color: gray;
            }

            td.col3 {
                background: green;
            }
    </style>
    <table class="table table-bordered">
        <tr>
            <td>Название</td>
            @foreach (var item in Model.RestrictionsPage.Restrictions)
            {
                if (item.ProjectId.Equals(RestrictionsPageViewModel.ProjectId))
                {
                    <td>@item.DateTime</td>
                }
            }
        </tr>
        <tr>
            <td>Финансы</td>

            @foreach (var item in Model.RestrictionsPage.Restrictions)
            {
                if (item.ProjectId.Equals(RestrictionsPageViewModel.ProjectId))
                {
                    @if (item.Finance != null && item.Finance.Equals("Хорошо"))
                    {
                        <td class="col3"></td>
                    }
                    else if (item.Finance != null && item.Finance.Equals("Плохо"))
                    {
                        <td class="col1"></td>
                    }
                    else
                    {
                        <td class="col2"></td>
                    }


                }
            }
        </tr>
        <tr>
            <td>Архитектура</td>
            @foreach (var item in Model.RestrictionsPage.Restrictions)
            {
                if (item.ProjectId.Equals(RestrictionsPageViewModel.ProjectId))
                {
                    @if (item.Architecture != null && item.Architecture.Equals("Хорошо"))
                    {
                        <td class="col3"></td>
                    }
                    else if (item.Architecture != null && item.Architecture.Equals("Плохо"))
                    {
                        <td class="col1"></td>
                    }
                    else
                    {
                        <td class="col2"></td>
                    }
                }
            }
        </tr>
        <tr>
            <td>Безопасность</td>
            @foreach (var item in Model.RestrictionsPage.Restrictions)
            {
                if (item.ProjectId.Equals(RestrictionsPageViewModel.ProjectId))
                {
                    @if (item.Safety != null && item.Safety.Equals("Хорошо"))
                    {
                        <td class="col3"></td>
                    }
                    else if (item.Safety != null && item.Safety.Equals("Плохо"))
                    {
                        <td class="col1"></td>
                    }
                    else
                    {
                        <td class="col2"></td>
                    }
                }
            }

        </tr>
        <tr>
            <td>Данные</td>
            @foreach (var item in Model.RestrictionsPage.Restrictions)
            {
                if (item.ProjectId.Equals(RestrictionsPageViewModel.ProjectId))
                {
                    @if (item.Data != null && item.Data.Equals("Хорошо"))
                    {
                        <td class="col3"></td>
                    }
                    else if (item.Data != null && item.Data.Equals("Плохо"))
                    {
                        <td class="col1"></td>
                    }
                    else
                    {
                        <td class="col2"></td>
                    }
                }
            }

        </tr>
        <tr>
            <td>Сроки</td>
            @foreach (var item in Model.RestrictionsPage.Restrictions)
            {
                if (item.ProjectId.Equals(RestrictionsPageViewModel.ProjectId))
                {
                    @if (item.RedLine != null && item.RedLine.Equals("Хорошо"))
                    {
                        <td class="col3"></td>
                    }
                    else if (item.RedLine != null && item.RedLine.Equals("Плохо"))
                    {
                        <td class="col1"></td>
                    }
                    else
                    {
                        <td class="col2"></td>
                    }
                }
            }

        <tr>
            <td>Документ</td>
            @foreach (var item in Model.RestrictionsPage.Restrictions)
            {
                if (item.ProjectId.Equals(RestrictionsPageViewModel.ProjectId))
                {
                    @if (item.Document != null && item.Document.Equals("Хорошо"))
                    {
                        <td class="col3"></td>
                    }
                    else if (item.Document != null && item.Document.Equals("Плохо"))
                    {
                        <td class="col1"></td>
                    }
                    else
                    {
                        <td class="col2"></td>
                    }
                }
            }
        </tr>
        <tr>
            <td>Инфраструктура</td>
            @foreach (var item in Model.RestrictionsPage.Restrictions)
            {
                if (item.ProjectId.Equals(RestrictionsPageViewModel.ProjectId))
                {
                    @if (item.Infrastructure != null && item.Infrastructure.Equals("Хорошо"))
                    {
                        <td class="col3"></td>
                    }
                    else if (item.Infrastructure != null && item.Infrastructure.Equals("Плохо"))
                    {
                        <td class="col1"></td>
                    }
                    else
                    {
                        <td class="col2"></td>
                    }
                }
            }

        <tr>
            <td>Лицензия</td>
            @foreach (var item in Model.RestrictionsPage.Restrictions)
            {
                if (item.ProjectId.Equals(RestrictionsPageViewModel.ProjectId))
                {
                    @if (item.License != null && item.License.Equals("Хорошо"))
                    {
                        <td class="col3"></td>
                    }
                    else if (item.License != null && item.License.Equals("Плохо"))
                    {
                        <td class="col1"></td>
                    }
                    else
                    {
                        <td class="col2"></td>
                    }
                }
            }

        </tr>

        <tr>
            <td>Изменение значения</td>
            @foreach (var item in Model.RestrictionsPage.Restrictions)
            {
                if (item.ProjectId.Equals(RestrictionsPageViewModel.ProjectId))
                {
                    <td>
                        @using (Html.BeginForm("EditTable", "Restrictions"))
                        {
                             
                            <input type="text" id="ss" name="id" value="@item.Id" style="display:none;"/>
                            <input type="submit" value="Изменить"  />
                        }
                    </td>
                }
            }

        </tr>

    </table>

    <hr />
    <a class="btn badge-light border-dark" href="/Restrictions/AddTable">Добавить таблицу</a>
</div>